services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    command: watchfiles --filter python 'uvicorn src.main:app --host 0.0.0.0 --port 8000'

  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env