# PostgreSQL
[postgres]
USER = "postgres"
PASSWORD = "changethis"

[security.password]
# Critical: This value must be kept secret and should be changed in production
# Losing or changing this value will invalidate all existing password hashes
# IMPORTANT: Replace the placeholder below with your own secure random string
# Recommended: Use a cryptographically secure random generator to create a
# string of at least 32 characters including numbers, letters, and symbols
PEPPER = "REPLACE_THIS_WITH_YOUR_OWN_SECRET_PEPPER_VALUE"

[security.auth]
# Recommended: Use a cryptographically secure random generator to create a
# string of at least 32 characters including numbers, letters, and symbols
JWT_SECRET = "REPLACE_THIS_WITH_YOUR_OWN_SECRET_VALUE"
# JWT_ALGORITHM can be set to "HS256", "HS384", "HS512", "RS256", "RS384", "RS512"
JWT_ALGORITHM = "HS256"
# SESSION_TTL_MIN must be at least 1 (number of minutes)
SESSION_TTL_MIN = 5
# SESSION_REFRESH_THRESHOLD must be a number (fraction, 0 < fraction < 1)
SESSION_REFRESH_THRESHOLD = 0.2

[security.cookies]
# Secure can be set to 0 or 1
# Choose 1 for production (secure=True, samesite="Strict")
SECURE = 0